apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: challenge
  hostPath:
    path: /data/mypv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-pvc
spec:
  storageClassName: challenge
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: challenge
  labels:
    name: challenge
spec:
  containers:
  - name: nginxcontainer
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name:  challenge
        mountPath:  /var/www/html
  volumes:
    - name:  challenge
      persistentVolumeClaim:
        claimName: challenge-pvc
